# Generated by Django 6.0 on 2025-12-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
