# Generated by Django 6.0 on 2025-12-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_description_alter_document_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
