# Generated by Django 6.0 on 2025-12-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='banner',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
