# Generated by Django 6.0 on 2025-12-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='banner',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
