# Generated by Django 6.0 on 2025-12-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_banner_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
